# Generated by Django 4.2 on 2025-04-22 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2025, 4, 22, 10, 3, 58, 350803, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
